{
    'name': 'Odoo 18 Fiscal Year & Lock Date',
    'version': '1.0.1',
    'category': 'Accounting',
    'summary': 'Odoo 18 Fiscal Year, Fiscal Year in Odoo 18, Lock Date in Odoo 18',
    'description': 'Odoo 18 Fiscal Year, Fiscal Year in Odoo 18',
    'sequence': '1',
    'website': 'https://alantechnologies.in/',
    'author': 'Alan Technologies',
    'maintainer': 'Alan Technologies',
    'license': 'LGPL-3',
    'support': 'support@alantechnologies.com',
    'depends': ['account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/change_lock_date.xml',
        'views/fiscal_year.xml',
        'views/settings.xml',
    ],
    'images': ['static/description/banner.png'],
}
